export const MOCK_USER_AVATAR = {
  lat: 36.3727,
  lng: 127.3602,
}

export const MOCK_MAP_OBJECTS = [
  {
    id: '1',
    type: 'library',
    name: 'Central Library',
    lat: 36.3727,
    lng: 127.3602,
    distanceMeters: 0,
    modelType: 'building',
    modelKey: 'library',
    modelUrl: '/models/tower/cat_tower_blue_01_muted_unlit.glb',
    modelScale: 0.72,
    rotationY: 0,
    radiusMeters: 180,
    description: 'Mock building anchor for roof cat placement.',
  },
  {
    id: '2',
    type: 'building',
    name: 'N1',
    lat: 36.3718,
    lng: 127.3611,
    distanceMeters: 130,
    modelType: 'building',
    modelKey: 'n1',
    modelUrl: '/models/tower/cat_tower_green_01_muted_unlit.glb',
    modelScale: 0.66,
    rotationY: 0,
    radiusMeters: 150,
    description: 'Mock nearby building object.',
  },
  {
    id: '3',
    type: 'dorm',
    name: 'Dormitory',
    lat: 36.3733,
    lng: 127.3615,
    distanceMeters: 135,
    modelType: 'building',
    modelKey: 'dorm',
    modelUrl: '/models/tower/cat_tower_pink_01_muted_unlit.glb',
    modelScale: 0.7,
    rotationY: 0,
    radiusMeters: 200,
    description: 'Mock roof object with a sleeping cat.',
  },
]

export const MOCK_CAT_ACTORS = [
  {
    catId: 'cat-101',
    displayType: 'discovered_cat',
    name: 'Mango',
    lat: 36.37262,
    lng: 127.36032,
    distanceMeters: 17,
    zoneId: '1',
    zoneName: 'Central Library',
    zoneType: 'library',
    surface: 'ground',
    anchorKey: 'ground_center',
    heightOffsetMeters: 0,
    movementRadiusMeters: 5,
    modelType: 'cat',
    modelKey: 'orange',
    modelUrl: '/models/cat.glb',
    modelScale: 0.82,
    animationKey: 'sit',
    latestSeenAt: '2026-07-06T18:24:00+09:00',
    mainImageUrl: 'https://images.unsplash.com/photo-1574158622682-e40e69881006?auto=format&fit=crop&w=500&q=80',
  },
  {
    catId: 'cat-202',
    displayType: 'discovered_cat',
    name: 'Berry',
    lat: 36.37175,
    lng: 127.36105,
    distanceMeters: 128,
    zoneId: '2',
    zoneName: 'N1',
    zoneType: 'building',
    surface: 'ground',
    anchorKey: 'entrance',
    heightOffsetMeters: 0,
    movementRadiusMeters: 7,
    modelType: 'cat',
    modelKey: 'white',
    modelUrl: '/models/cat.glb',
    modelScale: 0.78,
    animationKey: 'sit',
    latestSeenAt: '2026-07-06T17:42:00+09:00',
    mainImageUrl: 'https://images.unsplash.com/photo-1511044568932-338cba0ad803?auto=format&fit=crop&w=500&q=80',
  },
  {
    catId: 'cat-303',
    displayType: 'discovered_cat',
    name: 'Bam',
    lat: 36.37338,
    lng: 127.36158,
    distanceMeters: 150,
    zoneId: '3',
    zoneName: 'Dormitory',
    zoneType: 'dorm',
    surface: 'ground',
    anchorKey: 'ground_edge',
    heightOffsetMeters: 0,
    movementRadiusMeters: 4,
    modelType: 'cat',
    modelKey: 'black',
    modelUrl: '/models/cat.glb',
    modelScale: 0.84,
    animationKey: 'sit',
    latestSeenAt: '2026-07-06T16:08:00+09:00',
    mainImageUrl: 'https://images.unsplash.com/photo-1543852786-1cf6624b9987?auto=format&fit=crop&w=500&q=80',
  },
]

export async function fetchMockMapObjects() {
  return { objects: MOCK_MAP_OBJECTS }
}

export async function fetchMockCatActors() {
  return { cats: MOCK_CAT_ACTORS }
}
